name: Build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      clean:
        description: 'Clean Cache'
        required: false
        default: 'false'
      cmake:
        description: 'use custom cmake'
        required: false
        default: 'false'
  push:
    branches:
      - main
    paths:
      - 'open.config'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  ROOTFS_URL: https://github.com/cstkingkey/build/releases/download/rootfs-2023.06.22
  CLANG_URL: https://github.com/cstkingkey/build/releases/download/clang-release%2F17.x-2024.05.19-0107/clang.tar.xz
  OSXCROSS_URL: https://github.com/cstkingkey/build/releases/download/osxcross-2023.06.23/osxcross.tar.xz
  XWIN_URL: https://github.com/cstkingkey/build/releases/download/xwin-2023.06.23
  CMAKE_VERSION: 3.29.3

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: mac
            arch: aarch64
          - os: mac
            arch: x86_64
          - os: win
            arch: aarch64
          - os: win
            arch: i686
          - os: win
            arch: x86_64
          - os: linux
            arch: aarch64
            deb_arch: arm64
          - os: linux
            arch: x86_64
            deb_arch: amd64
          - os: linux
            arch: i686
            deb_arch: i386
          - os: linux
            arch: powerpc64le
            deb_arch: ppc64el
          # lld issue https://github.com/llvm/llvm-project/issues/58377  
          - os: linux
            arch: mips64el
            deb_arch: mips64el
            abi: abi64
          - os: linux
            arch: arm
            deb_arch: armhf
            abi: eabihf
          - os: linux
            arch: arm
            deb_arch: armel
            abi: eabi
          # lld issue https://github.com/llvm/llvm-project/issues/57097  
          - os: linux
            arch: s390x
            deb_arch: s390x
          - os: linux
            arch: mipsel
            deb_arch: mipsel
          - os: linux
            arch: mips
            deb_arch: mips

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      id: env
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        export OS=${{ matrix.os }}
        export ARCH=${{ matrix.arch }}
        export ABI=${{ matrix.abi }}
        export deb_arch=${{ matrix.deb_arch }}
        $GITHUB_WORKSPACE/entry.sh $GITHUB_WORKSPACE/install_package.sh
        echo "::set-output name=status::success"
        
    - name: Install cmake
      id: env-cmake
      if: github.event.inputs.cmake == 'true' && !cancelled()
      run: |
        curl -sSL https://cmake.org/files/LatestRelease/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz | tar -xz
        sudo cp -r cmake*/* /usr/local/
        echo "::set-output name=status::success"

    - name: Build and package
      id: build
      if: steps.env.outputs.status == 'success' && !cancelled()
      run: |
        git clone https://github.com/fltk-rs/fltk-rs --recurse-submodules
        cd fltk-rs
        export OS=${{ matrix.os }}
        export ARCH=${{ matrix.arch }}
        export ABI=${{ matrix.abi }}
        . $GITHUB_WORKSPACE/entry.sh
        $GITHUB_WORKSPACE/entry.sh $GITHUB_WORKSPACE/build.sh
        tar cJf fltk-${RUST_TARGET}.tar.xz target/${RUST_TARGET}/release/examples
        echo "ROOTFS=$PWD/fltk-${RUST_TARGET}.tar.xz" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
            TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Create tag
      id: tag
      if: steps.build.outputs.status == 'success' && !cancelled()
      run: |
        touch release.txt
        echo "fltk" >> release.txt
        echo "::set-output name=release_tag::fltk-$(date +"%Y.%m.%d")"
        echo "::set-output name=status::success"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: |
          ${{ env.ROOTFS }}

    
